name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        env:
          IMAGE_NAME: my-app
        run: |
          docker build -t $IMAGE_NAME:latest .
      - name: Test Docker image
        env:
          IMAGE_NAME: my-app
        run: |
          docker run --rm $IMAGE_NAME:latest python -c "print('Docker image built successfully!')"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest test.py
